# action.yaml
name: 'MS Teams Notifier Action'
description: 'A Github Action that sends notification to the MS Teams'
branding:
  icon: "activity"
  color: "blue"

inputs:
  github_token: #Github token needs to be passed from Actions calling this
    description: 'GitHub token'
    required: true 
    default: ${{ github.token }}
  teams_channel_webhook_url:
    description: 'MS Teams Channel webhook URI'
    required: false
  teams_channel_botflow_url:
    description: 'MS Teams Bot Flow URI'
    required: false
  repo_server_url:
    description: 'Repository server URL'
    required: false
    default: ${{ github.server_url }}
  repo_name:
    description: 'Repository name'
    required: false
    default: ${{github.repository}}
  github_sha:
    description: 'Github SHA'
    required: false
    default: ${{github.sha}}
  run_id:
    description: 'Workflow run ID '
    required: false
    default: ${{github.run_id}}
  run_number:
    description: 'Workflow run number '
    required: false
    default: ${{github.run_number}}
  github_branch:
    description: 'Branch name'
    required: false
    default: ${{ github.ref_name }}
runs:
  using: 'composite'
  steps:
    # - name: Install Python
    #   uses: actions/setup-python@v5
    #   with:
    #     python-version: '3.11.1'
    #     token: ${{ inputs.github_token }}
    - name: Sends a notification to ms teams
      id: send-msteams
      env:
        REPO_SERVER_URL: ${{ inputs.repo_server_url }}
        REPO_NAME: ${{ inputs.repo_name }}
        GITHUB_SHA: ${{ inputs.github_sha }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
        RUN_ID: ${{ inputs.run_id }}
        RUN_NUMBER: ${{ inputs.run_number }}
        TEAMS_CHANNEL_WEBHOOK_URL: ${{ inputs.teams_channel_webhook_url }}
        TEAMS_CHANNEL_BOTFLOW_URL: ${{ inputs.teams_channel_botflow_url }}
        GITHUB_BRANCH: ${{ inputs.github_branch }}
      run: |
        cd ${{github.action_path}}
        pip install -r requirements.txt --use-pep517
        python3 src/main.py
      shell: bash
