name: MS Teams Notification
on:
  push:
    branches: ['main']
    paths: ['docs/**']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Microsoft Teams Notifications
        uses: ./
        with:
          webhook_uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
