name: MS Teams Notification
on:
  push:
    branches: ['main']
    paths: ['MyFolder/**']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        if: always()
        with:
         webhook: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
