name: MS Teams Notification
on:
  push:
    branches: ['main']
    paths: ['docs/**']

jobs:
  success: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./
      with: 
        github-token: ${{ github.token }}
        ms-teams-webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
        notification-summary: Changes are committed
        notification-color: 17a2b8
        timezone: America/Denver 
    