name: MS Teams Notification
on:
  push:
    branches: ['main']
jobs:
  send-msteams-notification:
    runs-on: ubuntu-latest
    name: Sends a notifications to MS Teams
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Notification
        if: always()
        id: send_notification
        uses: ./
        with:
          github_token: ${{ github.token }}
