name: MS Teams Notification
on:
  push:
    branches: ['main']
    paths: ['**/**']
jobs:
  send-msteams-notification:
    runs-on: ubuntu-latest
    name: Sends a notifications to MS Teams
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Notification
        if: always()
        id: send_notification
        uses: ./
        with:
          github_token: ${{ github.token }}
          #Use webhook url if you want to receive group notification 
          teams_channel_webhook_url: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          #Use botflow url if you want to receive group notification 
          teams_channel_botflow_url: ${{ secrets.MS_TEAMS_BOT_FLOW_URI }}
